import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";
import { AuthCodeRedirect } from "@/components/auth/auth-code-redirect";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="font-sans antialiased"
      >
        <Suspense fallback={null}>
          <AuthCodeRedirect />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
